### ISSUE TITLE
Cannot find Mosek

### ISSUE THREAD

**Issue by valentinguenon** [KIKI007/DESIA#1]
I have downloaded DESIA project to use it in Visual Studio 2019.
But when i build the CMakeLists, I have this error : 

 Could NOT find MOSEK (missing: MOSEK_LIBRARIES)		C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake	165

How I can install MOSEK ?

Thanks

**Comment by KIKI007** [comment]
Hey Valentinguenon, sorry, it has been a long time but now I get rid of the mosek and I hope it can run on windows.

If you have a linux and mac, it should compile without any problem.
